package com.briup.apps.poll.bean;

public class Class {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_class.id
     *
     * @mbg.generated Mon Jun 25 16:38:17 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_class.name
     *
     * @mbg.generated Mon Jun 25 16:38:17 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_class.grade_id
     *
     * @mbg.generated Mon Jun 25 16:38:17 CST 2018
     */
    private Long gradeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_class.charge_id
     *
     * @mbg.generated Mon Jun 25 16:38:17 CST 2018
     */
    private Long chargeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_class.description
     *
     * @mbg.generated Mon Jun 25 16:38:17 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_class.id
     *
     * @return the value of poll_class.id
     *
     * @mbg.generated Mon Jun 25 16:38:17 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_class.id
     *
     * @param id the value for poll_class.id
     *
     * @mbg.generated Mon Jun 25 16:38:17 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_class.name
     *
     * @return the value of poll_class.name
     *
     * @mbg.generated Mon Jun 25 16:38:17 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_class.name
     *
     * @param name the value for poll_class.name
     *
     * @mbg.generated Mon Jun 25 16:38:17 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_class.grade_id
     *
     * @return the value of poll_class.grade_id
     *
     * @mbg.generated Mon Jun 25 16:38:17 CST 2018
     */
    public Long getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_class.grade_id
     *
     * @param gradeId the value for poll_class.grade_id
     *
     * @mbg.generated Mon Jun 25 16:38:17 CST 2018
     */
    public void setGradeId(Long gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_class.charge_id
     *
     * @return the value of poll_class.charge_id
     *
     * @mbg.generated Mon Jun 25 16:38:17 CST 2018
     */
    public Long getChargeId() {
        return chargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_class.charge_id
     *
     * @param chargeId the value for poll_class.charge_id
     *
     * @mbg.generated Mon Jun 25 16:38:17 CST 2018
     */
    public void setChargeId(Long chargeId) {
        this.chargeId = chargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_class.description
     *
     * @return the value of poll_class.description
     *
     * @mbg.generated Mon Jun 25 16:38:17 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_class.description
     *
     * @param description the value for poll_class.description
     *
     * @mbg.generated Mon Jun 25 16:38:17 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}